
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Using the Supabase project details from config.toml
const SUPABASE_URL = "https://ujquhridgymkfcpvyqml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcXVocmlkZ3lta2ZjcHZ5cW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDgwNzcsImV4cCI6MjA2MzIyNDA3N30.p6Jcs99taIrPJyWswu2JR1Bfw6_oxXvxI_qbOBfMNdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
